Repository skni-kod/StudentreFrontend, pull requests merged in 2021-12, with the labels that each got.

#34 chore: change eslint configuration file format
  .eslintrc.js
  package-lock.json
Labels: refactoring

#35 feat: dark theme
  package-lock.json
  package.json
  src/pages/_app.tsx
  tailwind.config.js
Labels: enhancement

#36 feat: sass support
  .vscode/css_custom_data.json
  .vscode/settings.json
  package-lock.json
  package.json
  src/pages/_app.tsx
  src/styles/globals.scss
Labels: enhancement

#37 refactor: improve logo
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/images/logo.svg
  public/images/logomark.svg
  public/images/logotype.svg
  public/mstile-150x150.png
  public/safari-pinned-tab.svg
  public/site.webmanifest
Labels: refactoring

#38 refactor: revamp tailwind theme
  src/components/logotype.tsx
  tailwind.config.js
Labels: refactoring

#39 docs: update authors section in README file
  README.md
Labels: documentation

#40 docs: fix incorrect logo source in README file
  README.md
Labels: documentation

#41 docs: update authors section in README file
  README.md
Labels: documentation

#42 chore: update absolute import paths
  .eslintrc.js
  tsconfig.json
Labels: refactoring

#43 feat: add clsx
  next-env.d.ts
  package-lock.json
  package.json
  src/components/logomark.tsx
  src/components/logotype.tsx
Labels: enhancement

#44 feat: add source sans 3 font
  public/fonts/Outfit-Medium.woff2
  public/fonts/Outfit-VariableFont_wght.ttf
  public/fonts/SourceSans3VF-Italic.ttf.woff2
  public/fonts/SourceSans3VF-Roman.ttf.woff2
  src/components/head.tsx
  src/styles/globals.scss
Labels: enhancement

#45 feat: tailwind 3
  .vscode/css_custom_data.json
  package-lock.json
  package.json
  src/styles/globals.scss
  tailwind.config.js
Labels: enhancement

#46 chore: remove unnecessarily strict eslint rules
  .eslintrc.js
Labels: refactoring

#47 chore: update eslint plugin tailwindcss
  package.json
Labels: enhancement

#48 refactor: gray palette
  tailwind.config.js
Labels: refactoring

#49 refactor: change default font to Jost*
  public/fonts/Jost-VF.ttf
  public/fonts/SourceSans3VF-Italic.ttf.woff2
  public/fonts/SourceSans3VF-Roman.ttf.woff2
  src/components/head.tsx
  src/styles/globals.scss
  tailwind.config.js
Labels: refactoring

#50 feat: add `useRenderCount` hook
  src/hooks/useRenderCount.ts
Labels: enhancement

#51 feat: add `useTypeSafeTheme` hook
  src/hooks/useTypeSafeTheme.ts
  src/types/theme.ts
Labels: enhancement
